### ISSUE TITLE
Slide with video background and sound enabled not auto played on Chrome

### ISSUE THREAD

**Issue by shaifeyna56** [mennolui/wp-foyer#30]
slide with video background not auto played on chromium browser or google chrome .. need to click on the page at browser manually to make the video play..

chromium browser version : 70.0.3538.77
wordpress version : 4.9.7
foyer plugin version : 1.6.0
video fomat tested : mkv mp4

**Comment by shaifeyna56** [comment]
found some link from google : https://productforums.google.com/forum/#!topic/chrome/LlaGhkScHls
best answer is adding code below after </video>
<script> 
    document.getElementById('vid').play(); 
</script> 

im not modify your code yet to test

**Comment by mennolui** [comment]
Hi @shaifeyna56, thanks for the bug report.

Do you mean video backgrounds never play for you?
Because video backgrounds still work for me on Chrome 70  / MacOS 10.14.

With the exception of this known issue: #31 (videos not playing when adding them to a display / channel that is already being displayed)

Could you give me as much input as possible, so I can maybe fix this? Eg. steps taken, when do they play and when don't they, what Chrome version / OS version, what happens when using other browsers (Firefox, Safari, Edge) and OS, etc.

**Comment by shaifeyna56** [comment]
its google chrome.. I googled and find they told only muted video will autoplay.. with sound will not autoplay.. I tested myself, its autoplay when mute the video if not muted, it not autoplay the video..

**Comment by mennolui** [comment]
Good to hear it works with that Autoplay policy setting changed!
